<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mix.MCP.Lib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ModelContextProtocol" Version="0.1.0-preview.10" />
    <PackageReference Include="ModelContextProtocol.AspNetCore" Version="0.1.0-preview.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\platform\mix.library\mix.library.csproj" />
  </ItemGroup>


</Project>
