// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mix.Database.Entities.QueueLog;

#nullable disable

namespace Mix.Database.Migrations.QueueLog.SqlServer
{
    [DbContext(typeof(SqlServerQueueLogDbContext))]
    partial class SqlServerQueueLogDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mix.Database.Entities.QueueLog.QueueLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id")
                        .HasDefaultValueSql("newid()");

                    b.Property<string>("Action")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("action");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("created_by");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("datetime")
                        .HasColumnName("created_date_time");

                    b.Property<string>("DataTypeFullName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("data_type_full_name");

                    b.Property<string>("Exception")
                        .HasColumnType("ntext")
                        .HasColumnName("exception");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime")
                        .HasColumnName("last_modified");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("modified_by");

                    b.Property<string>("Note")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("note");

                    b.Property<string>("ObjectData")
                        .HasColumnType("ntext")
                        .HasColumnName("object_data");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<Guid?>("QueueMessageId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("queue_message_id");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("state")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("StringData")
                        .HasColumnType("ntext")
                        .HasColumnName("string_data");

                    b.Property<string>("SubscriptionId")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Subscriptions")
                        .HasColumnType("ntext")
                        .HasColumnName("subscriptions");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TopicId")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("topic_id");

                    b.HasKey("Id")
                        .HasName("pk_queue_log");

                    b.ToTable("mix_queue_log", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
