// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mix.Database.Entities.Settings;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mix.Database.Migrations.Settings.SqlServer
{
    [DbContext(typeof(SqlServerGlobalSettingContext))]
    [Migration("20250130063406_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mix.Database.Entities.Settings.MixGlobalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(4000)")
                        .HasColumnName("description")
                        .UseCollation("Vietnamese_CI_AS")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("display_name")
                        .UseCollation("Vietnamese_CI_AS")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsEncrypt")
                        .HasColumnType("bit")
                        .HasColumnName("is_encrypt");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime")
                        .HasColumnName("last_modified");

                    b.Property<int>("TenantId")
                        .HasColumnType("int")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SectionName")
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("section_name")
                        .UseCollation("Vietnamese_CI_AS")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("service_name")
                        .UseCollation("Vietnamese_CI_AS")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Settings")
                        .HasColumnType("ntext")
                        .HasColumnName("settings")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("system_name")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixGlobalSetting");

                    b.ToTable("mix_global_setting", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
