apiVersion: v1
kind: Secret
metadata:
  name: mixcore-secrets
  namespace: mixcore
type: Opaque
data:
  sqlserver-password: UEBzc3cwcmQ=  # Base64 encoded "P@ssw0rd"
  mysql-password: cm9vdA==  # Base64 encoded "root"
  redis-password: UEBzc3cwcmQ=  # Base64 encoded "P@ssw0rd" 