apiVersion: v1
kind: PersistentVolume
metadata:
  name: mixcore-sqlserver-pv
  namespace: mixcore
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/mixcore/sqlserver
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mixcore-sqlserver-pvc
  namespace: mixcore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mixcore-mysql-pv
  namespace: mixcore
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/mixcore/mysql
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mixcore-mysql-pvc
  namespace: mixcore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mixcore-redis-pv
  namespace: mixcore
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  hostPath:
    path: /data/mixcore/redis
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mixcore-redis-pvc
  namespace: mixcore
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard 