<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>Mix.Mqtt.Lib</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MQTTnet" Version="5.0.1.1416" />
    <PackageReference Include="MQTTnet.AspNetCore" Version="5.0.1.1416" />
    <PackageReference Include="MQTTnet.Extensions.ManagedClient" Version="4.3.7.1207" />
    <PackageReference Include="MQTTnet.Extensions.Rpc" Version="5.0.1.1416" />
    <PackageReference Include="MQTTnet.Extensions.WebSocket4Net" Version="4.3.7.1207" />
    <PackageReference Include="MQTTnet.Server" Version="5.0.1.1416" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\mix.shared\mix.shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Client\" />
  </ItemGroup>

</Project>
