// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mix.Database.Entities.Settings;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mix.Database.Migrations.Settings.Postgres
{
    [DbContext(typeof(PostgresGlobalSettingContext))]
    [Migration("20250130061042_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Mix.Database.Entities.Settings.MixGlobalSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .HasColumnName("description")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("display_name")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsEncrypt")
                        .HasColumnType("boolean")
                        .HasColumnName("is_encrypt");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<int>("TenantId")
                        .HasColumnType("integer")
                        .HasColumnName("tenant_id");

                    b.Property<string>("SectionName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("section_name")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("service_name")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Settings")
                        .HasColumnType("text")
                        .HasColumnName("settings")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .HasColumnType("varchar(250)")
                        .HasColumnName("system_name")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixGlobalSetting");

                    b.ToTable("mix_global_setting", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
