import * as i0 from "@angular/core";
import * as i1 from "@angular/common";
import * as i2 from "@angular/forms";
import * as i3 from "@taiga-ui/kit";
import * as i4 from "@taiga-ui/core";
import * as i5 from "@taiga-ui/cdk";
import * as i6 from "@taiga-ui/addon-editor";
import * as i7 from "angular-tabler-icons";
export declare class ShareModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<ShareModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<ShareModule, never, [typeof i1.CommonModule, typeof i2.FormsModule, typeof i2.ReactiveFormsModule, typeof i3.TuiInputModule, typeof i3.TuiSelectModule, typeof i3.TuiComboBoxModule, typeof i3.TuiMultiSelectModule, typeof i4.TuiSvgModule, typeof i3.TuiAvatarModule, typeof i4.TuiButtonModule, typeof i5.TuiActiveZoneModule, typeof i3.TuiAvatarModule, typeof i3.TuiMarkerIconModule, typeof i4.TuiHostedDropdownModule, typeof i4.TuiLinkModule, typeof i4.TuiSvgModule, typeof i5.TuiLetModule, typeof i4.TuiDataListModule, typeof i3.TuiDataListWrapperModule, typeof i4.TuiLabelModule, typeof i3.TuiIslandModule, typeof i3.TuiInputModule, typeof i3.TuiTextAreaModule, typeof i4.TuiLinkModule, typeof i4.TuiButtonModule, typeof i3.TuiCheckboxLabeledModule, typeof i4.TuiTextfieldControllerModule, typeof i4.TuiLabelModule, typeof i3.TuiFieldErrorModule, typeof i3.TuiTagModule, typeof i3.TuiStepperModule, typeof i3.TuiStringifyPipeModule, typeof i3.TuiStringifyContentPipeModule, typeof i3.TuiBadgeModule, typeof i3.TuiTabsModule, typeof i4.TuiErrorModule, typeof i3.TuiProgressModule, typeof i4.TuiDialogModule, typeof i4.TuiTooltipModule, typeof i4.TuiHintModule, typeof i4.TuiHintControllerModule, typeof i3.TuiRadioBlockModule, typeof i4.TuiGroupModule, typeof i6.TuiEditorModule, typeof i6.TuiEditorNewModule, typeof i3.TuiInputDateRangeModule, typeof i3.TuiAvatarModule, typeof i3.TuiToggleModule, typeof i3.TuiAccordionModule, typeof i4.TuiDataListModule, typeof i7.TablerIconsModule], [typeof i1.CommonModule, typeof i2.FormsModule, typeof i2.ReactiveFormsModule, typeof i3.TuiInputModule, typeof i3.TuiSelectModule, typeof i3.TuiComboBoxModule, typeof i3.TuiMultiSelectModule, typeof i4.TuiSvgModule, typeof i3.TuiAvatarModule, typeof i4.TuiButtonModule, typeof i5.TuiActiveZoneModule, typeof i3.TuiAvatarModule, typeof i3.TuiMarkerIconModule, typeof i4.TuiHostedDropdownModule, typeof i4.TuiLinkModule, typeof i4.TuiSvgModule, typeof i5.TuiLetModule, typeof i4.TuiDataListModule, typeof i3.TuiDataListWrapperModule, typeof i4.TuiLabelModule, typeof i3.TuiIslandModule, typeof i3.TuiInputModule, typeof i3.TuiTextAreaModule, typeof i4.TuiLinkModule, typeof i4.TuiButtonModule, typeof i3.TuiCheckboxLabeledModule, typeof i4.TuiTextfieldControllerModule, typeof i4.TuiLabelModule, typeof i3.TuiFieldErrorModule, typeof i3.TuiTagModule, typeof i3.TuiStepperModule, typeof i3.TuiStringifyPipeModule, typeof i3.TuiStringifyContentPipeModule, typeof i3.TuiBadgeModule, typeof i3.TuiTabsModule, typeof i4.TuiErrorModule, typeof i3.TuiProgressModule, typeof i4.TuiDialogModule, typeof i4.TuiTooltipModule, typeof i4.TuiHintModule, typeof i4.TuiHintControllerModule, typeof i3.TuiRadioBlockModule, typeof i4.TuiGroupModule, typeof i6.TuiEditorModule, typeof i6.TuiEditorNewModule, typeof i3.TuiInputDateRangeModule, typeof i3.TuiAvatarModule, typeof i3.TuiToggleModule, typeof i3.TuiAccordionModule, typeof i4.TuiDataListModule, typeof i7.TablerIconsModule]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<ShareModule>;
}
