// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mix.Database.Entities;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Mix.Database.Migrations.PostgresqlMixCms
{
    [DbContext(typeof(PostgresqlMixCmsContext))]
    [Migration("20220316025636_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "uuid-ossp");
            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixConfiguration");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixConfiguration");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixConfigurationContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DefaultContent")
                        .IsRequired()
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MixConfigurationId")
                        .HasColumnType("integer");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Specificulture")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixConfigurationContent");

                    b.HasIndex("MixConfigurationId");

                    b.HasIndex("MixCultureId");

                    b.ToTable("MixConfigurationContent");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixCulture", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Icon")
                        .HasColumnType("varchar(4000)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Lcid")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Specificulture")
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixCulture");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixCulture");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixDatabaseId")
                        .HasColumnType("integer");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixData");

                    b.HasIndex("MixDatabaseId");

                    b.ToTable("MixData");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDatabase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixDatabase");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixDatabase");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDatabaseColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Configurations")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DefaultValue")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixDatabaseId")
                        .HasColumnType("integer");

                    b.Property<string>("MixDatabaseName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixDatabaseColumn");

                    b.HasIndex("MixDatabaseId");

                    b.ToTable("MixDatabaseColumn");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDataContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("int");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MixDataId")
                        .HasColumnType("uuid");

                    b.Property<int>("MixDatabaseId")
                        .HasColumnType("integer");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("text");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoKeywords")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Specificulture")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixDataContent");

                    b.HasIndex("MixCultureId");

                    b.HasIndex("MixDataId");

                    b.ToTable("MixDataContent");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDataContentAssociation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid>("DataContentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("GuidParentId")
                        .HasColumnType("uuid");

                    b.Property<int?>("IntParentId")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<int>("MixDatabaseId")
                        .HasColumnType("integer");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("text");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ParentType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Specificulture")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixDataContentAssociation");

                    b.HasIndex("MixCultureId");

                    b.ToTable("MixDataContentAssociation");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDataContentValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool?>("BooleanValue")
                        .HasColumnType("boolean");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DataType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<DateTime?>("DateTimeValue")
                        .HasColumnType("timestamp without time zone");

                    b.Property<double?>("DoubleValue")
                        .HasColumnType("double precision");

                    b.Property<string>("EncryptKey")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("EncryptType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("EncryptValue")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int?>("IntegerValue")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MixDataContentId")
                        .HasColumnType("uuid");

                    b.Property<int>("MixDatabaseColumnId")
                        .HasColumnType("integer");

                    b.Property<string>("MixDatabaseColumnName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("MixDatabaseId")
                        .HasColumnType("integer");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<Guid>("ParentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Specificulture")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("StringValue")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixDataContentValue");

                    b.HasIndex("MixCultureId");

                    b.HasIndex("MixDataContentId");

                    b.HasIndex("MixDatabaseColumnId");

                    b.ToTable("MixDataContentValue");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDomain", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixDomain");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixDomain");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixLanguage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixLanguage");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixLanguage");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixLanguageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("DefaultContent")
                        .IsRequired()
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<int?>("MixLanguageId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Specificulture")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixLanguageContent");

                    b.HasIndex("MixCultureId");

                    b.HasIndex("MixLanguageId");

                    b.ToTable("MixLanguageContent");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixModule");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixModule");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModuleContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("int");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MixDataContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("text");

                    b.Property<int?>("MixModuleId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("PageSize")
                        .HasColumnType("integer");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoKeywords")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text");

                    b.Property<string>("SimpleDataColumns")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Specificulture")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .HasColumnType("varchar(250)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixModuleContent");

                    b.HasIndex("MixCultureId");

                    b.HasIndex("MixDataContentId");

                    b.HasIndex("MixModuleId");

                    b.ToTable("MixModuleContent");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModuleData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("int");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<int?>("MixModuleContentId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoKeywords")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text");

                    b.Property<string>("SimpleDataColumns")
                        .HasColumnType("varchar(4000)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Specificulture")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Value")
                        .HasColumnType("varchar(4000)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixModuleData");

                    b.HasIndex("MixCultureId");

                    b.HasIndex("MixModuleContentId");

                    b.ToTable("MixModuleData");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModulePostAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeftId")
                        .HasColumnType("integer");

                    b.Property<int?>("MixModuleContentId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RightId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixModulePostAssociation");

                    b.HasIndex("MixModuleContentId");

                    b.ToTable("MixModulePostAssociation");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("MixPostContentId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixPage");

                    b.HasIndex("MixPostContentId");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixPage");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("int");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MixDataContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("text");

                    b.Property<int?>("MixPageId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int?>("PageSize")
                        .HasColumnType("integer");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoKeywords")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Specificulture")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixPageContent");

                    b.HasIndex("MixCultureId");

                    b.HasIndex("MixDataContentId");

                    b.HasIndex("MixPageId");

                    b.ToTable("MixPageContent");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPageModuleAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeftId")
                        .HasColumnType("integer");

                    b.Property<int?>("MixPageContentId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RightId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixPageModuleAssociation");

                    b.HasIndex("MixPageContentId");

                    b.ToTable("MixPageModuleAssociation");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPagePostAssociation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("LeftId")
                        .HasColumnType("integer");

                    b.Property<int?>("MixPageContentId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<int>("RightId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixPagePostAssociation");

                    b.HasIndex("MixPageContentId");

                    b.ToTable("MixPagePostAssociation");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixPost");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixPost");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPostContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClassName")
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Excerpt")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Image")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int?>("LayoutId")
                        .HasColumnType("int");

                    b.Property<int>("MixCultureId")
                        .HasColumnType("integer");

                    b.Property<Guid?>("MixDataContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("text");

                    b.Property<int?>("MixPostContentId")
                        .HasColumnType("integer");

                    b.Property<int?>("MixPostId")
                        .HasColumnType("integer");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("ParentId")
                        .HasColumnType("integer");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PublishedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("SeoDescription")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoKeywords")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoName")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SeoTitle")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Specificulture")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int?>("TemplateId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixPostContent");

                    b.HasIndex("MixCultureId");

                    b.HasIndex("MixDataContentId");

                    b.HasIndex("MixPostContentId");

                    b.HasIndex("MixPostId");

                    b.ToTable("MixPostContent");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("FileFolder")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("FolderType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<int>("MixThemeId")
                        .HasColumnType("integer");

                    b.Property<string>("MixThemeName")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Scripts")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("Styles")
                        .IsRequired()
                        .HasColumnType("text")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixTemplate");

                    b.HasIndex("MixThemeId");

                    b.ToTable("MixViewTemplate");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixTenant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PrimaryDomain")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.HasKey("Id")
                        .HasName("PK_MixTenant");

                    b.ToTable("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixTheme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<Guid?>("MixDataContentId")
                        .HasColumnType("uuid");

                    b.Property<string>("MixDatabaseName")
                        .HasColumnType("text");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<string>("PreviewUrl")
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("SystemName")
                        .HasColumnType("text");

                    b.HasKey("Id")
                        .HasName("PK_MixTheme");

                    b.HasIndex("MixDataContentId");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixTheme");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixUrlAlias", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alias")
                        .HasColumnType("text");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<DateTime>("CreatedDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Description")
                        .HasColumnType("varchar(4000)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .UseCollation("und-x-icu")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("MixTenantId")
                        .HasColumnType("integer");

                    b.Property<string>("ModifiedBy")
                        .HasColumnType("varchar(250)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<Guid?>("SourceContentGuidId")
                        .HasColumnType("uuid");

                    b.Property<int?>("SourceContentId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasAnnotation("MySql:CharSet", "utf8");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("PK_MixUrlAlias");

                    b.HasIndex("MixTenantId");

                    b.ToTable("MixUrlAlias");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixConfiguration", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany()
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixConfigurationContent", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixConfiguration", "MixConfiguration")
                        .WithMany("MixConfigurationContents")
                        .HasForeignKey("MixConfigurationId");

                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixConfiguration");

                    b.Navigation("MixCulture");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixCulture", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany()
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixData", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixDatabase", "MixDatabase")
                        .WithMany()
                        .HasForeignKey("MixDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixDatabase");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDatabase", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany("MixDatabases")
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDatabaseColumn", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixDatabase", "MixDatabase")
                        .WithMany("MixDatabaseColumns")
                        .HasForeignKey("MixDatabaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixDatabase");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDataContent", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mix.Database.Entities.Cms.MixData", "MixData")
                        .WithMany("MixDataContents")
                        .HasForeignKey("MixDataId");

                    b.Navigation("MixCulture");

                    b.Navigation("MixData");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDataContentAssociation", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixCulture");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDataContentValue", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mix.Database.Entities.Cms.MixDataContent", "MixDataContent")
                        .WithMany("MixDataContentValues")
                        .HasForeignKey("MixDataContentId");

                    b.HasOne("Mix.Database.Entities.Cms.MixDatabaseColumn", "MixDatabaseColumn")
                        .WithMany()
                        .HasForeignKey("MixDatabaseColumnId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("MixCulture");

                    b.Navigation("MixDataContent");

                    b.Navigation("MixDatabaseColumn");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDomain", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany()
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixLanguage", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany()
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixLanguageContent", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mix.Database.Entities.Cms.MixLanguage", "MixLanguage")
                        .WithMany("MixLanguageContents")
                        .HasForeignKey("MixLanguageId");

                    b.Navigation("MixCulture");

                    b.Navigation("MixLanguage");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModule", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany("MixModules")
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModuleContent", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mix.Database.Entities.Cms.MixDataContent", "MixDataContent")
                        .WithMany()
                        .HasForeignKey("MixDataContentId");

                    b.HasOne("Mix.Database.Entities.Cms.MixModule", "MixModule")
                        .WithMany("MixModuleContents")
                        .HasForeignKey("MixModuleId");

                    b.Navigation("MixCulture");

                    b.Navigation("MixDataContent");

                    b.Navigation("MixModule");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModuleData", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mix.Database.Entities.Cms.MixModuleContent", "MixModuleContent")
                        .WithMany()
                        .HasForeignKey("MixModuleContentId");

                    b.Navigation("MixCulture");

                    b.Navigation("MixModuleContent");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModulePostAssociation", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixModuleContent", null)
                        .WithMany("MixPostContents")
                        .HasForeignKey("MixModuleContentId");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPage", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixPostContent", null)
                        .WithMany("MixPages")
                        .HasForeignKey("MixPostContentId");

                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany("MixPages")
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPageContent", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mix.Database.Entities.Cms.MixDataContent", "MixDataContent")
                        .WithMany()
                        .HasForeignKey("MixDataContentId");

                    b.HasOne("Mix.Database.Entities.Cms.MixPage", "MixPage")
                        .WithMany("MixPageContents")
                        .HasForeignKey("MixPageId");

                    b.Navigation("MixCulture");

                    b.Navigation("MixDataContent");

                    b.Navigation("MixPage");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPageModuleAssociation", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixPageContent", null)
                        .WithMany("MixModuleContents")
                        .HasForeignKey("MixPageContentId");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPagePostAssociation", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixPageContent", null)
                        .WithMany("MixPostContents")
                        .HasForeignKey("MixPageContentId");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPost", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany("MixPosts")
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPostContent", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixCulture", "MixCulture")
                        .WithMany()
                        .HasForeignKey("MixCultureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Mix.Database.Entities.Cms.MixDataContent", "MixDataContent")
                        .WithMany()
                        .HasForeignKey("MixDataContentId");

                    b.HasOne("Mix.Database.Entities.Cms.MixPostContent", null)
                        .WithMany("MixPostContents")
                        .HasForeignKey("MixPostContentId");

                    b.HasOne("Mix.Database.Entities.Cms.MixPost", "MixPost")
                        .WithMany("MixPostContents")
                        .HasForeignKey("MixPostId");

                    b.Navigation("MixCulture");

                    b.Navigation("MixDataContent");

                    b.Navigation("MixPost");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixTemplate", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTheme", "MixTheme")
                        .WithMany("MixViewTemplates")
                        .HasForeignKey("MixThemeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTheme");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixTheme", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixDataContent", "MixDataContent")
                        .WithMany()
                        .HasForeignKey("MixDataContentId");

                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany()
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixDataContent");

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixUrlAlias", b =>
                {
                    b.HasOne("Mix.Database.Entities.Cms.MixTenant", "MixTenant")
                        .WithMany()
                        .HasForeignKey("MixTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MixTenant");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixConfiguration", b =>
                {
                    b.Navigation("MixConfigurationContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixData", b =>
                {
                    b.Navigation("MixDataContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDatabase", b =>
                {
                    b.Navigation("MixDatabaseColumns");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixDataContent", b =>
                {
                    b.Navigation("MixDataContentValues");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixLanguage", b =>
                {
                    b.Navigation("MixLanguageContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModule", b =>
                {
                    b.Navigation("MixModuleContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixModuleContent", b =>
                {
                    b.Navigation("MixPostContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPage", b =>
                {
                    b.Navigation("MixPageContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPageContent", b =>
                {
                    b.Navigation("MixModuleContents");

                    b.Navigation("MixPostContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPost", b =>
                {
                    b.Navigation("MixPostContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixPostContent", b =>
                {
                    b.Navigation("MixPages");

                    b.Navigation("MixPostContents");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixTenant", b =>
                {
                    b.Navigation("MixDatabases");

                    b.Navigation("MixModules");

                    b.Navigation("MixPages");

                    b.Navigation("MixPosts");
                });

            modelBuilder.Entity("Mix.Database.Entities.Cms.MixTheme", b =>
                {
                    b.Navigation("MixViewTemplates");
                });
#pragma warning restore 612, 618
        }
    }
}
